name: Tests

on:
  workflow_dispatch:
  push:
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          pixi_environment: testminimal
          pixi_task: test

        - os: ubuntu-latest
          pixi_environment: testpyold
          pixi_task: test

        - os: ubuntu-latest
          pixi_environment: testpynew
          pixi_task: test

        - os: macos-latest
          pixi_environment: testpymid
          pixi_task: test

        - os: windows-latest
          pixi_environment: testpymid
          pixi_task: test

        - os: ubuntu-latest
          pixi_environment: testtorch
          pixi_task: test-backends

        - os: ubuntu-latest
          pixi_environment: testjax
          pixi_task: test-backends

        - os: ubuntu-latest
          pixi_environment: testtensorflow
          pixi_task: test-backends

    steps:
    - uses: actions/checkout@v6

    - uses: prefix-dev/setup-pixi@v0.9.4
      with:
        environments: ${{ matrix.pixi_environment }}

    - name: Test with pytest
      run: pixi run -e ${{ matrix.pixi_environment }} ${{ matrix.pixi_task }}

    - name: Report to codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
